# Generated by Django 2.0.2 on 2018-10-26 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gust',
            new_name='Guest',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='realname',
            new_name='real_name',
        ),
    ]
